void mainchess1();
void mainchess2();
int mov_valido2(struct COORDENADAS Curr,struct COORDENADAS New);
 int mov_valido(struct COORDENADAS,struct COORDENADAS);
 int rn_enjake2(struct COORDENADAS);
 int rb_enjake2(struct COORDENADAS);
 int rn_enjake();
 int rb_enjake();
 int n_total_mov_validos();
 int b_total_mov_validos();
 void n_jakemate();
 void b_jakemate();
 void n_jake();
 void b_jake();
 void n_reyaogado();
 void b_reyaogado();
 void n_promocion();
 void b_promocion();
void tabla();
void guardador();

